// Code generated by Slice Machine. DO NOT EDIT.

import { SliceComponentProps } from "@prismicio/react";
import { TextBlock } from "./TextBlock";
import Manifesto from "./Manifesto";

type SliceComponents = {
  text_block: typeof TextBlock;
  manifesto: typeof Manifesto;
};

export const components: SliceComponents = {
  text_block: TextBlock,
  manifesto: Manifesto,
};
