// Code generated by Slice Machine. DO NOT EDIT.

import { SliceComponentProps } from "@prismicio/react";
import { TextBlock } from "./TextBlock";

export const components = {
  text_block: TextBlock,
} as Record<string, (props: SliceComponentProps) => JSX.Element>;
